
CREATE DATABASE IF NOT EXISTS projetoQR;

USE projetoQR;

CREATE TABLE aluno (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    idade INT NOT NULL,
    senha VARCHAR(255) NOT NULL
);
